### ISSUE TITLE
Feature request: When glued at the bottom (or any other direction), add transition to the scrolling

### ISSUE THREAD

**Issue by anubhav193** [Luegg/angularjs-scroll-glue#58] opened 2017-03-30 12:41 UTC
Drawing inspiration from google allo and other bots, it would be great if there would be a way to add transition to the scrolling action so that if the scroll position is at the end, it would **transition** to the new scroll position after an element is appended.

**Comment by oliversalzburg** [comment] 2017-03-30 22:41
Duplicate of #32

**Closed as completed by oliversalzburg** 2017-03-30 22:41 UTC
